"""empty message

Revision ID: 560e72f537a7
Revises: 436e629e3afb
Create Date: 2026-02-04 20:47:08.520207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560e72f537a7'
down_revision = '436e629e3afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_authors_surname'), ['surname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_surname'))
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
