"""empty message

Revision ID: 65926ae9bacd
Revises: 7e941e716393
Create Date: 2026-02-04 22:41:27.325971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65926ae9bacd'
down_revision = '7e941e716393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_authors_surname'), ['surname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_surname'))
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
