"""empty message

Revision ID: 67c2454d6936
Revises: 436e629e3afb
Create Date: 2026-02-04 22:34:21.235144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c2454d6936'
down_revision = '436e629e3afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_authors_surname'), ['surname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_surname'))
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
